// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: pb/usersvc/v1/usersvc.pb.go

package mock

import (
	context "context"
	sync "sync"

	github_com_stkr89_livegig_common_pb_usersvc_v1 "github.com/stkr89/livegig-common/pb/usersvc/v1"
	google_golang_org_grpc "google.golang.org/grpc"
)

// MockUserSvcClient is a mock of UserSvcClient interface
type MockUserSvcClient struct {
	lockCreate sync.Mutex
	CreateFunc func(ctx context.Context, in *github_com_stkr89_livegig_common_pb_usersvc_v1.CreateRequest, opts ...google_golang_org_grpc.CallOption) (*github_com_stkr89_livegig_common_pb_usersvc_v1.UserResponse, error)

	lockFindByEmail sync.Mutex
	FindByEmailFunc func(ctx context.Context, in *github_com_stkr89_livegig_common_pb_usersvc_v1.FindByEmailRequest, opts ...google_golang_org_grpc.CallOption) (*github_com_stkr89_livegig_common_pb_usersvc_v1.UserResponse, error)

	calls struct {
		Create []struct {
			Ctx  context.Context
			In   *github_com_stkr89_livegig_common_pb_usersvc_v1.CreateRequest
			Opts []google_golang_org_grpc.CallOption
		}
		FindByEmail []struct {
			Ctx  context.Context
			In   *github_com_stkr89_livegig_common_pb_usersvc_v1.FindByEmailRequest
			Opts []google_golang_org_grpc.CallOption
		}
	}
}

// Create mocks base method by wrapping the associated func.
func (m *MockUserSvcClient) Create(ctx context.Context, in *github_com_stkr89_livegig_common_pb_usersvc_v1.CreateRequest, opts ...google_golang_org_grpc.CallOption) (*github_com_stkr89_livegig_common_pb_usersvc_v1.UserResponse, error) {
	m.lockCreate.Lock()
	defer m.lockCreate.Unlock()

	if m.CreateFunc == nil {
		panic("mocker: MockUserSvcClient.CreateFunc is nil but MockUserSvcClient.Create was called.")
	}

	call := struct {
		Ctx  context.Context
		In   *github_com_stkr89_livegig_common_pb_usersvc_v1.CreateRequest
		Opts []google_golang_org_grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}

	m.calls.Create = append(m.calls.Create, call)

	return m.CreateFunc(ctx, in, opts...)
}

// CreateCalled returns true if Create was called at least once.
func (m *MockUserSvcClient) CreateCalled() bool {
	m.lockCreate.Lock()
	defer m.lockCreate.Unlock()

	return len(m.calls.Create) > 0
}

// CreateCalls returns the calls made to Create.
func (m *MockUserSvcClient) CreateCalls() []struct {
	Ctx  context.Context
	In   *github_com_stkr89_livegig_common_pb_usersvc_v1.CreateRequest
	Opts []google_golang_org_grpc.CallOption
} {
	m.lockCreate.Lock()
	defer m.lockCreate.Unlock()

	return m.calls.Create
}

// FindByEmail mocks base method by wrapping the associated func.
func (m *MockUserSvcClient) FindByEmail(ctx context.Context, in *github_com_stkr89_livegig_common_pb_usersvc_v1.FindByEmailRequest, opts ...google_golang_org_grpc.CallOption) (*github_com_stkr89_livegig_common_pb_usersvc_v1.UserResponse, error) {
	m.lockFindByEmail.Lock()
	defer m.lockFindByEmail.Unlock()

	if m.FindByEmailFunc == nil {
		panic("mocker: MockUserSvcClient.FindByEmailFunc is nil but MockUserSvcClient.FindByEmail was called.")
	}

	call := struct {
		Ctx  context.Context
		In   *github_com_stkr89_livegig_common_pb_usersvc_v1.FindByEmailRequest
		Opts []google_golang_org_grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}

	m.calls.FindByEmail = append(m.calls.FindByEmail, call)

	return m.FindByEmailFunc(ctx, in, opts...)
}

// FindByEmailCalled returns true if FindByEmail was called at least once.
func (m *MockUserSvcClient) FindByEmailCalled() bool {
	m.lockFindByEmail.Lock()
	defer m.lockFindByEmail.Unlock()

	return len(m.calls.FindByEmail) > 0
}

// FindByEmailCalls returns the calls made to FindByEmail.
func (m *MockUserSvcClient) FindByEmailCalls() []struct {
	Ctx  context.Context
	In   *github_com_stkr89_livegig_common_pb_usersvc_v1.FindByEmailRequest
	Opts []google_golang_org_grpc.CallOption
} {
	m.lockFindByEmail.Lock()
	defer m.lockFindByEmail.Unlock()

	return m.calls.FindByEmail
}

// Reset resets the calls made to the mocked methods.
func (m *MockUserSvcClient) Reset() {
	m.lockCreate.Lock()
	m.calls.Create = nil
	m.lockCreate.Unlock()
	m.lockFindByEmail.Lock()
	m.calls.FindByEmail = nil
	m.lockFindByEmail.Unlock()
}
