// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/orgsvc/v1/orgsvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// create org response
type CreateResponse struct {
	// unique id of org
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AdminUserId          string   `protobuf:"bytes,3,opt,name=adminUserId,proto3" json:"adminUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a94a9b62e908a3f, []int{0}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateResponse) GetAdminUserId() string {
	if m != nil {
		return m.AdminUserId
	}
	return ""
}

// create org request
type CreateRequest struct {
	// name or org
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// user id of admin
	AdminUserId          string   `protobuf:"bytes,2,opt,name=adminUserId,proto3" json:"adminUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a94a9b62e908a3f, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetAdminUserId() string {
	if m != nil {
		return m.AdminUserId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateResponse)(nil), "pb.orgsvc.v1.CreateResponse")
	proto.RegisterType((*CreateRequest)(nil), "pb.orgsvc.v1.CreateRequest")
}

func init() { proto.RegisterFile("pb/orgsvc/v1/orgsvc.proto", fileDescriptor_0a94a9b62e908a3f) }

var fileDescriptor_0a94a9b62e908a3f = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x48, 0xd2, 0xcf,
	0x2f, 0x4a, 0x2f, 0x2e, 0x4b, 0xd6, 0x2f, 0x33, 0x84, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x78, 0x0a, 0x92, 0xf4, 0xa0, 0x02, 0x65, 0x86, 0x4a, 0x61, 0x5c, 0x7c, 0xce, 0x45, 0xa9,
	0x89, 0x25, 0xa9, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79,
	0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x11, 0x30, 0x5b, 0x48, 0x81, 0x8b, 0x3b, 0x31, 0x25, 0x37,
	0x33, 0x2f, 0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x45, 0x82, 0x19, 0x2c, 0x85, 0x2c, 0xa4, 0xe4, 0xca,
	0xc5, 0x0b, 0x33, 0xb7, 0xb0, 0x34, 0xb5, 0xb8, 0x04, 0x6e, 0x0c, 0x23, 0x6e, 0x63, 0x98, 0x30,
	0x8c, 0x31, 0xf2, 0xe7, 0x62, 0xf3, 0x2f, 0x4a, 0x0f, 0x2e, 0x4b, 0x16, 0x72, 0xe5, 0x62, 0x83,
	0x18, 0x28, 0x24, 0xad, 0x87, 0xec, 0x03, 0x3d, 0x14, 0x6b, 0xa4, 0x64, 0xb0, 0x4b, 0x42, 0xfc,
	0xa6, 0xc4, 0xe0, 0xc4, 0x17, 0xc5, 0x83, 0x1c, 0x34, 0x49, 0x6c, 0xe0, 0x40, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x50, 0xa7, 0xe5, 0x6c, 0x31, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrgSvcClient is the client API for OrgSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrgSvcClient interface {
	// create new org
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type orgSvcClient struct {
	cc *grpc.ClientConn
}

func NewOrgSvcClient(cc *grpc.ClientConn) OrgSvcClient {
	return &orgSvcClient{cc}
}

func (c *orgSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.orgsvc.v1.OrgSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgSvcServer is the server API for OrgSvc service.
type OrgSvcServer interface {
	// create new org
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedOrgSvcServer can be embedded to have forward compatible implementations.
type UnimplementedOrgSvcServer struct {
}

func (*UnimplementedOrgSvcServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterOrgSvcServer(s *grpc.Server, srv OrgSvcServer) {
	s.RegisterService(&_OrgSvc_serviceDesc, srv)
}

func _OrgSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.orgsvc.v1.OrgSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrgSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.orgsvc.v1.OrgSvc",
	HandlerType: (*OrgSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrgSvc_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/orgsvc/v1/orgsvc.proto",
}
