// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/usersvc/v1/usersvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// register user request
type RegisterRequest struct {
	// user
	User                 *UserType `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *UserType {
	if m != nil {
		return m.User
	}
	return nil
}

// register user response
type RegisterResponse struct {
	// user
	User                 *UserType    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetUser() *UserType {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// find user request
type FindRequest struct {
	// user
	User                 *UserType `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindRequest) Reset()         { *m = FindRequest{} }
func (m *FindRequest) String() string { return proto.CompactTextString(m) }
func (*FindRequest) ProtoMessage()    {}
func (*FindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{2}
}

func (m *FindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRequest.Unmarshal(m, b)
}
func (m *FindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRequest.Marshal(b, m, deterministic)
}
func (m *FindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRequest.Merge(m, src)
}
func (m *FindRequest) XXX_Size() int {
	return xxx_messageInfo_FindRequest.Size(m)
}
func (m *FindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindRequest proto.InternalMessageInfo

func (m *FindRequest) GetUser() *UserType {
	if m != nil {
		return m.User
	}
	return nil
}

// find user response
type FindResponse struct {
	// user
	User                 *UserType    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FindResponse) Reset()         { *m = FindResponse{} }
func (m *FindResponse) String() string { return proto.CompactTextString(m) }
func (*FindResponse) ProtoMessage()    {}
func (*FindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{3}
}

func (m *FindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResponse.Unmarshal(m, b)
}
func (m *FindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResponse.Marshal(b, m, deterministic)
}
func (m *FindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResponse.Merge(m, src)
}
func (m *FindResponse) XXX_Size() int {
	return xxx_messageInfo_FindResponse.Size(m)
}
func (m *FindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindResponse proto.InternalMessageInfo

func (m *FindResponse) GetUser() *UserType {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *FindResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// user type
type UserType struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AwsUserSub           string   `protobuf:"bytes,5,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserType) Reset()         { *m = UserType{} }
func (m *UserType) String() string { return proto.CompactTextString(m) }
func (*UserType) ProtoMessage()    {}
func (*UserType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{4}
}

func (m *UserType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserType.Unmarshal(m, b)
}
func (m *UserType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserType.Marshal(b, m, deterministic)
}
func (m *UserType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserType.Merge(m, src)
}
func (m *UserType) XXX_Size() int {
	return xxx_messageInfo_UserType.Size(m)
}
func (m *UserType) XXX_DiscardUnknown() {
	xxx_messageInfo_UserType.DiscardUnknown(m)
}

var xxx_messageInfo_UserType proto.InternalMessageInfo

func (m *UserType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserType) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserType) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserType) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserType) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{5}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "pb.usersvc.v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.usersvc.v1.RegisterResponse")
	proto.RegisterType((*FindRequest)(nil), "pb.usersvc.v1.FindRequest")
	proto.RegisterType((*FindResponse)(nil), "pb.usersvc.v1.FindResponse")
	proto.RegisterType((*UserType)(nil), "pb.usersvc.v1.UserType")
	proto.RegisterType((*ErrorType)(nil), "pb.usersvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/usersvc/v1/usersvc.proto", fileDescriptor_5686a1f77a855eff) }

var fileDescriptor_5686a1f77a855eff = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x4d, 0x4f, 0x83, 0x50,
	0x10, 0x14, 0xfa, 0xbd, 0xb5, 0xd6, 0x6c, 0x4c, 0x24, 0xd4, 0xd4, 0x86, 0x53, 0x13, 0x13, 0x6a,
	0xeb, 0xcd, 0x83, 0x89, 0x9a, 0x7a, 0xd3, 0x03, 0xea, 0xc5, 0x1b, 0x94, 0xb5, 0x21, 0x29, 0x85,
	0xbe, 0x05, 0x8c, 0x7f, 0xc1, 0xbf, 0xe0, 0x9f, 0x35, 0xbc, 0xf6, 0xf5, 0x83, 0xe8, 0x41, 0x0f,
	0xde, 0xd8, 0x99, 0xd9, 0x79, 0x93, 0x65, 0xa0, 0x13, 0x7b, 0x83, 0x94, 0x49, 0x70, 0x36, 0x19,
	0x64, 0x43, 0xf5, 0x69, 0xc7, 0x22, 0x4a, 0x22, 0x6c, 0xc5, 0x9e, 0xad, 0x90, 0x6c, 0x68, 0x5d,
	0x41, 0xdb, 0xa1, 0x69, 0xc0, 0x09, 0x09, 0x87, 0x16, 0x29, 0x71, 0x82, 0x67, 0x50, 0xce, 0x05,
	0x86, 0xd6, 0xd3, 0xfa, 0xcd, 0xd1, 0xb1, 0xbd, 0xb3, 0x60, 0x3f, 0x33, 0x89, 0xa7, 0xf7, 0x98,
	0x1c, 0x29, 0xb2, 0x16, 0x70, 0xb8, 0xd9, 0xe7, 0x38, 0x9a, 0x33, 0xfd, 0xca, 0x00, 0xcf, 0xa1,
	0x4a, 0x42, 0x44, 0x82, 0x0d, 0xbd, 0x57, 0xea, 0x37, 0x47, 0x46, 0x41, 0x3e, 0xce, 0x49, 0xa9,
	0x5f, 0xe9, 0xac, 0x4b, 0x68, 0xde, 0x05, 0x73, 0xff, 0x4f, 0x71, 0x43, 0xd8, 0x5f, 0xee, 0xfe,
	0x4f, 0xd4, 0x0f, 0x0d, 0xea, 0xca, 0x04, 0x0f, 0x40, 0x0f, 0x7c, 0xf9, 0x52, 0xc3, 0xd1, 0x03,
	0x1f, 0x4f, 0xa0, 0xf1, 0x1a, 0x08, 0x4e, 0x1e, 0xdc, 0x90, 0x0c, 0x5d, 0xc2, 0x1b, 0x00, 0x4d,
	0xa8, 0xcf, 0xdc, 0x15, 0x59, 0x92, 0xe4, 0x7a, 0xc6, 0x23, 0xa8, 0x50, 0xe8, 0x06, 0x33, 0xa3,
	0x2c, 0x89, 0xe5, 0x80, 0x5d, 0x00, 0xf7, 0x8d, 0xf3, 0xe7, 0x1e, 0x53, 0xcf, 0xa8, 0x48, 0x6a,
	0x0b, 0xb1, 0xc6, 0xd0, 0x58, 0x27, 0xcc, 0xc5, 0x9c, 0xb8, 0x49, 0xca, 0xb7, 0x91, 0x4f, 0x32,
	0x54, 0xc5, 0xd9, 0x42, 0xd0, 0x80, 0x5a, 0x48, 0xcc, 0xee, 0x54, 0x45, 0x53, 0xe3, 0xe8, 0x53,
	0x83, 0x9a, 0xb4, 0xcc, 0x26, 0x78, 0x0d, 0xe5, 0xfc, 0x9c, 0x68, 0x16, 0x2e, 0xb1, 0xf5, 0x7f,
	0xcc, 0xce, 0xb7, 0xdc, 0xf2, 0xfe, 0xd6, 0x1e, 0xde, 0x43, 0x5d, 0x15, 0x08, 0xbb, 0x05, 0x69,
	0xa1, 0x99, 0xe6, 0xe9, 0x8f, 0xbc, 0xb2, 0xbb, 0x69, 0xbf, 0xb4, 0x76, 0xda, 0xef, 0x55, 0x65,
	0xed, 0x2f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x70, 0xc5, 0xb3, 0xcf, 0x15, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	// find user email
	Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error)
	// register user
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) Find(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*FindResponse, error) {
	out := new(FindResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	// find user email
	Find(context.Context, *FindRequest) (*FindResponse, error)
	// register user
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) Find(ctx context.Context, req *FindRequest) (*FindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (*UnimplementedUserSvcServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).Find(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.usersvc.v1.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _UserSvc_Find_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserSvc_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/usersvc/v1/usersvc.proto",
}
