// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/usersvc/v1/usersvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// find user by email request
type FindByEmailRequest struct {
	// email address of user
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByEmailRequest) Reset()         { *m = FindByEmailRequest{} }
func (m *FindByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*FindByEmailRequest) ProtoMessage()    {}
func (*FindByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{0}
}

func (m *FindByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByEmailRequest.Unmarshal(m, b)
}
func (m *FindByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByEmailRequest.Marshal(b, m, deterministic)
}
func (m *FindByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByEmailRequest.Merge(m, src)
}
func (m *FindByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_FindByEmailRequest.Size(m)
}
func (m *FindByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByEmailRequest proto.InternalMessageInfo

func (m *FindByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// register user request
type RegisterRequest struct {
	// first name of user
	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// email address of user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// aws cognito id of user
	AwsUserSub           string   `protobuf:"bytes,4,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

// register user response
type UserResponse struct {
	// unique id of user
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string       `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string       `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string       `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AwsUserSub           string       `protobuf:"bytes,5,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

func (m *UserResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{3}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*FindByEmailRequest)(nil), "pb.usersvc.v1.FindByEmailRequest")
	proto.RegisterType((*RegisterRequest)(nil), "pb.usersvc.v1.RegisterRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.usersvc.v1.UserResponse")
	proto.RegisterType((*ErrorType)(nil), "pb.usersvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/usersvc/v1/usersvc.proto", fileDescriptor_5686a1f77a855eff) }

var fileDescriptor_5686a1f77a855eff = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xb6, 0xe5, 0x7f, 0x10, 0x49, 0x26, 0x1e, 0x1a, 0x30, 0x04, 0x7b, 0x22, 0x1e, 0x8a, 0xe0,
	0x1b, 0x60, 0x30, 0xf1, 0xa2, 0x49, 0xd5, 0x8b, 0xb7, 0x96, 0x8e, 0xa4, 0x09, 0xd0, 0xba, 0xb3,
	0xad, 0xe1, 0xe8, 0xc3, 0xf8, 0x1e, 0x3e, 0x9a, 0x69, 0xe9, 0x42, 0x5b, 0x83, 0xde, 0xf6, 0xfb,
	0xc9, 0xce, 0xb7, 0xb3, 0x1f, 0xf4, 0x43, 0x77, 0x1c, 0x31, 0x09, 0x8e, 0x17, 0xe3, 0x78, 0xa2,
	0x8e, 0x56, 0x28, 0x02, 0x19, 0x60, 0x27, 0x74, 0x2d, 0xc5, 0xc4, 0x13, 0xf3, 0x0a, 0xf0, 0xce,
	0xdf, 0x78, 0xb3, 0xed, 0x7c, 0xed, 0xf8, 0x2b, 0x9b, 0xde, 0x23, 0x62, 0x89, 0xe7, 0x50, 0xa3,
	0x04, 0x1b, 0xda, 0x50, 0x1b, 0xb5, 0xec, 0x1d, 0x30, 0x3f, 0x35, 0xe8, 0xda, 0xb4, 0xf4, 0x59,
	0x92, 0x50, 0xce, 0x0b, 0x68, 0xbd, 0xf9, 0x82, 0xe5, 0x83, 0xb3, 0xa6, 0xcc, 0x7d, 0x20, 0xb0,
	0x07, 0xcd, 0x95, 0x93, 0x89, 0x7a, 0x2a, 0xee, 0xf1, 0x61, 0x46, 0x25, 0x37, 0x03, 0x07, 0x00,
	0xce, 0x07, 0xbf, 0x30, 0x89, 0xa7, 0xc8, 0x35, 0xaa, 0xa9, 0x94, 0x63, 0xcc, 0x6f, 0x0d, 0x4e,
	0x93, 0xb3, 0x4d, 0x1c, 0x06, 0x1b, 0x26, 0x3c, 0x03, 0xdd, 0xf7, 0xb2, 0xc9, 0xba, 0xef, 0x15,
	0x03, 0xe9, 0x7f, 0x05, 0xaa, 0x1c, 0x0b, 0x54, 0x3d, 0x1e, 0xa8, 0x56, 0x0e, 0x84, 0xd7, 0x50,
	0x27, 0x21, 0x02, 0xc1, 0x46, 0x7d, 0x58, 0x19, 0xb5, 0xa7, 0x86, 0x55, 0x58, 0xb0, 0x35, 0x4f,
	0xc4, 0xe7, 0x6d, 0x48, 0x76, 0xe6, 0x33, 0xe7, 0xd0, 0xda, 0x93, 0xc9, 0xf5, 0x2c, 0x1d, 0x19,
	0xf1, 0x6d, 0xe0, 0xed, 0x16, 0x58, 0xb3, 0x73, 0x0c, 0x1a, 0xd0, 0x58, 0x13, 0xb3, 0xb3, 0x54,
	0x8f, 0x51, 0x70, 0xfa, 0xa5, 0x41, 0x23, 0x0d, 0x11, 0x2f, 0xf0, 0x1e, 0x9a, 0xea, 0x63, 0x70,
	0x50, 0x0a, 0x50, 0xfa, 0xb1, 0x5e, 0xbf, 0xa4, 0xe7, 0xb7, 0x69, 0x9e, 0xe0, 0x23, 0xb4, 0x73,
	0x85, 0xc0, 0xcb, 0x92, 0xfb, 0x77, 0x59, 0xfe, 0xb9, 0x70, 0xd6, 0x7d, 0xed, 0x14, 0xfa, 0xe8,
	0xd6, 0xd3, 0x22, 0xde, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x58, 0x6f, 0x6a, 0xa7, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	// register user
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// find user by email
	FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/FindByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	// register user
	Register(context.Context, *RegisterRequest) (*UserResponse, error)
	// find user by email
	FindByEmail(context.Context, *FindByEmailRequest) (*UserResponse, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) Register(ctx context.Context, req *RegisterRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserSvcServer) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmail not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_FindByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).FindByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/FindByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).FindByEmail(ctx, req.(*FindByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.usersvc.v1.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserSvc_Register_Handler,
		},
		{
			MethodName: "FindByEmail",
			Handler:    _UserSvc_FindByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/usersvc/v1/usersvc.proto",
}
