// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/usersvc/v1/usersvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// delete user response
type DeleteResonse struct {
	Errors               []*ErrorType `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DeleteResonse) Reset()         { *m = DeleteResonse{} }
func (m *DeleteResonse) String() string { return proto.CompactTextString(m) }
func (*DeleteResonse) ProtoMessage()    {}
func (*DeleteResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{0}
}

func (m *DeleteResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResonse.Unmarshal(m, b)
}
func (m *DeleteResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResonse.Marshal(b, m, deterministic)
}
func (m *DeleteResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResonse.Merge(m, src)
}
func (m *DeleteResonse) XXX_Size() int {
	return xxx_messageInfo_DeleteResonse.Size(m)
}
func (m *DeleteResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResonse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResonse proto.InternalMessageInfo

func (m *DeleteResonse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// delete user request
type DeleteRequest struct {
	// id of user
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{1}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// find user by email request
type FindByEmailRequest struct {
	// email address of user
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByEmailRequest) Reset()         { *m = FindByEmailRequest{} }
func (m *FindByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*FindByEmailRequest) ProtoMessage()    {}
func (*FindByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{2}
}

func (m *FindByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByEmailRequest.Unmarshal(m, b)
}
func (m *FindByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByEmailRequest.Marshal(b, m, deterministic)
}
func (m *FindByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByEmailRequest.Merge(m, src)
}
func (m *FindByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_FindByEmailRequest.Size(m)
}
func (m *FindByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByEmailRequest proto.InternalMessageInfo

func (m *FindByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

// register user request
type CreateRequest struct {
	// first name of user
	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// email address of user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// aws cognito id of user
	AwsUserSub           string   `protobuf:"bytes,4,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{3}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

// register user response
type UserResponse struct {
	// unique id of user
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string       `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string       `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string       `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	AwsUserSub           string       `protobuf:"bytes,5,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{4}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

func (m *UserResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5686a1f77a855eff, []int{5}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteResonse)(nil), "pb.usersvc.v1.DeleteResonse")
	proto.RegisterType((*DeleteRequest)(nil), "pb.usersvc.v1.DeleteRequest")
	proto.RegisterType((*FindByEmailRequest)(nil), "pb.usersvc.v1.FindByEmailRequest")
	proto.RegisterType((*CreateRequest)(nil), "pb.usersvc.v1.CreateRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.usersvc.v1.UserResponse")
	proto.RegisterType((*ErrorType)(nil), "pb.usersvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/usersvc/v1/usersvc.proto", fileDescriptor_5686a1f77a855eff) }

var fileDescriptor_5686a1f77a855eff = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x4e, 0xf2, 0x50,
	0x10, 0xfd, 0x5a, 0xa0, 0x7c, 0x0c, 0x56, 0x93, 0x1b, 0x17, 0x0d, 0x10, 0xc5, 0xae, 0x88, 0x8b,
	0x22, 0xf8, 0x04, 0x82, 0x65, 0xa9, 0x49, 0xd5, 0x8d, 0xbb, 0x5b, 0x3a, 0x9a, 0x26, 0x40, 0xeb,
	0x9d, 0xb6, 0x86, 0x95, 0xaf, 0xe6, 0xeb, 0xf8, 0x16, 0xa6, 0x7f, 0xf4, 0x87, 0xa0, 0xee, 0xee,
	0xcc, 0x39, 0xf7, 0xcc, 0xb9, 0x33, 0x73, 0xa1, 0xef, 0xdb, 0xe3, 0x90, 0x50, 0x50, 0xb4, 0x1c,
	0x47, 0x93, 0xfc, 0x68, 0xf8, 0xc2, 0x0b, 0x3c, 0xa6, 0xfa, 0xb6, 0x91, 0x67, 0xa2, 0x89, 0x7e,
	0x03, 0xea, 0x2d, 0xae, 0x30, 0x40, 0x0b, 0xc9, 0xdb, 0x10, 0xb2, 0x2b, 0x50, 0x50, 0x08, 0x4f,
	0x90, 0x26, 0x0d, 0x1b, 0xa3, 0xee, 0x54, 0x33, 0x2a, 0x17, 0x0c, 0x33, 0x06, 0x1f, 0xb7, 0x3e,
	0x5a, 0x19, 0x4f, 0x3f, 0x2f, 0x24, 0xde, 0x42, 0xa4, 0x80, 0x1d, 0x83, 0xec, 0x3a, 0x9a, 0x34,
	0x94, 0x46, 0x1d, 0x4b, 0x76, 0x1d, 0xfd, 0x12, 0xd8, 0xc2, 0xdd, 0x38, 0xb3, 0xad, 0xb9, 0xe6,
	0xee, 0x2a, 0x67, 0x9d, 0x42, 0x0b, 0xe3, 0x38, 0x23, 0xa6, 0x81, 0xfe, 0x01, 0xea, 0x5c, 0x20,
	0x2f, 0xc4, 0x06, 0xd0, 0x79, 0x71, 0x05, 0x05, 0x77, 0x7c, 0x8d, 0x19, 0xb5, 0x48, 0xb0, 0x1e,
	0xfc, 0x5f, 0xf1, 0x0c, 0x94, 0x13, 0x70, 0x17, 0x17, 0x05, 0x1a, 0xa5, 0x02, 0xec, 0x0c, 0x80,
	0xbf, 0xd3, 0x13, 0xa1, 0x78, 0x08, 0x6d, 0xad, 0x99, 0x40, 0xa5, 0x8c, 0xfe, 0x29, 0xc1, 0x51,
	0x7c, 0xb6, 0x90, 0xfc, 0xa4, 0x21, 0xb5, 0xd7, 0x54, 0x0d, 0xc9, 0x3f, 0x19, 0x6a, 0x1c, 0x32,
	0xd4, 0x3c, 0x6c, 0xa8, 0x55, 0x37, 0x54, 0x1a, 0x88, 0xf2, 0xc7, 0x81, 0x98, 0xd0, 0xd9, 0x25,
	0x63, 0x79, 0x0a, 0x78, 0x10, 0xd2, 0xdc, 0x73, 0xd2, 0x06, 0xb6, 0xac, 0x52, 0x86, 0x69, 0xd0,
	0x5e, 0x23, 0x11, 0x7f, 0xcd, 0x1f, 0x93, 0x87, 0xd3, 0x2f, 0x09, 0xda, 0x89, 0x89, 0x68, 0xc9,
	0x4c, 0x50, 0xd2, 0xb1, 0xb0, 0x41, 0xad, 0x7c, 0x65, 0x5a, 0xbd, 0x7e, 0x0d, 0x2d, 0x77, 0x52,
	0xff, 0xc7, 0xee, 0xa1, 0x5b, 0xda, 0x04, 0x76, 0x51, 0x63, 0xef, 0x6f, 0xc9, 0x6f, 0x82, 0x0b,
	0x50, 0xd2, 0xdd, 0xdb, 0xf3, 0x55, 0x59, 0xc9, 0xde, 0x21, 0x94, 0x52, 0x9d, 0xd9, 0xc9, 0xb3,
	0x5a, 0xf9, 0x34, 0xb6, 0x92, 0xfc, 0x96, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x45,
	0x07, 0xb7, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSvcClient is the client API for UserSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSvcClient interface {
	// register user
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// find user by email
	FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// delete user
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResonse, error)
}

type userSvcClient struct {
	cc *grpc.ClientConn
}

func NewUserSvcClient(cc *grpc.ClientConn) UserSvcClient {
	return &userSvcClient{cc}
}

func (c *userSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) FindByEmail(ctx context.Context, in *FindByEmailRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/FindByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSvcClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResonse, error) {
	out := new(DeleteResonse)
	err := c.cc.Invoke(ctx, "/pb.usersvc.v1.UserSvc/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSvcServer is the server API for UserSvc service.
type UserSvcServer interface {
	// register user
	Create(context.Context, *CreateRequest) (*UserResponse, error)
	// find user by email
	FindByEmail(context.Context, *FindByEmailRequest) (*UserResponse, error)
	// delete user
	Delete(context.Context, *DeleteRequest) (*DeleteResonse, error)
}

// UnimplementedUserSvcServer can be embedded to have forward compatible implementations.
type UnimplementedUserSvcServer struct {
}

func (*UnimplementedUserSvcServer) Create(ctx context.Context, req *CreateRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserSvcServer) FindByEmail(ctx context.Context, req *FindByEmailRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByEmail not implemented")
}
func (*UnimplementedUserSvcServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResonse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUserSvcServer(s *grpc.Server, srv UserSvcServer) {
	s.RegisterService(&_UserSvc_serviceDesc, srv)
}

func _UserSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_FindByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).FindByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/FindByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).FindByEmail(ctx, req.(*FindByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSvc_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSvcServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.usersvc.v1.UserSvc/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSvcServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.usersvc.v1.UserSvc",
	HandlerType: (*UserSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserSvc_Create_Handler,
		},
		{
			MethodName: "FindByEmail",
			Handler:    _UserSvc_FindByEmail_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserSvc_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/usersvc/v1/usersvc.proto",
}
