// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ticketsvc/v1/ticketsvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ticket response
type TicketResponse struct {
	// unique id of ticket
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrgId       string `protobuf:"bytes,4,opt,name=orgId,proto3" json:"orgId,omitempty"`
	CreatedBy   string `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// reference id of ticket
	ReferenceId          string       `protobuf:"bytes,6,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TicketResponse) Reset()         { *m = TicketResponse{} }
func (m *TicketResponse) String() string { return proto.CompactTextString(m) }
func (*TicketResponse) ProtoMessage()    {}
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{0}
}

func (m *TicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketResponse.Unmarshal(m, b)
}
func (m *TicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketResponse.Marshal(b, m, deterministic)
}
func (m *TicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketResponse.Merge(m, src)
}
func (m *TicketResponse) XXX_Size() int {
	return xxx_messageInfo_TicketResponse.Size(m)
}
func (m *TicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TicketResponse proto.InternalMessageInfo

func (m *TicketResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TicketResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TicketResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TicketResponse) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *TicketResponse) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *TicketResponse) GetReferenceId() string {
	if m != nil {
		return m.ReferenceId
	}
	return ""
}

func (m *TicketResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// create ticket request
type CreateRequest struct {
	// title of ticket
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// description of ticket
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// org id of ticket
	OrgId string `protobuf:"bytes,3,opt,name=orgId,proto3" json:"orgId,omitempty"`
	// id of user creating this ticket
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *CreateRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{2}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TicketResponse)(nil), "pb.ticketsvc.v1.TicketResponse")
	proto.RegisterType((*CreateRequest)(nil), "pb.ticketsvc.v1.CreateRequest")
	proto.RegisterType((*ErrorType)(nil), "pb.ticketsvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/ticketsvc/v1/ticketsvc.proto", fileDescriptor_9d6faa99461a7b25) }

var fileDescriptor_9d6faa99461a7b25 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x6e, 0xf2, 0x30,
	0x10, 0x85, 0xff, 0x04, 0x08, 0xca, 0xa0, 0x1f, 0x54, 0xab, 0x0b, 0x0b, 0x55, 0x80, 0xb2, 0x62,
	0x15, 0x04, 0xbd, 0x01, 0x88, 0x05, 0xea, 0x2e, 0x65, 0x51, 0x75, 0x07, 0xf6, 0x14, 0x59, 0x6d,
	0xb1, 0x6b, 0x9b, 0x48, 0xa8, 0xb7, 0xed, 0x49, 0xaa, 0xd8, 0xa5, 0x09, 0x41, 0x65, 0xf9, 0xde,
	0xcb, 0xcc, 0xe4, 0xf3, 0x0c, 0x0c, 0xd5, 0x76, 0x62, 0x05, 0x7b, 0x45, 0x6b, 0x72, 0x36, 0xc9,
	0xa7, 0xa5, 0x48, 0x95, 0x96, 0x56, 0x92, 0x9e, 0xda, 0xa6, 0xa5, 0x97, 0x4f, 0x93, 0xaf, 0x00,
	0xba, 0x6b, 0x67, 0x64, 0x68, 0x94, 0xdc, 0x1b, 0x24, 0x5d, 0x08, 0x05, 0xa7, 0xc1, 0x28, 0x18,
	0xc7, 0x59, 0x28, 0x38, 0xb9, 0x85, 0x96, 0x15, 0xf6, 0x0d, 0x69, 0xe8, 0x2c, 0x2f, 0xc8, 0x08,
	0x3a, 0x1c, 0x0d, 0xd3, 0x42, 0x59, 0x21, 0xf7, 0xb4, 0xe1, 0xb2, 0xaa, 0x55, 0xd4, 0x49, 0xbd,
	0x5b, 0x71, 0xda, 0xf4, 0x75, 0x4e, 0x90, 0x3b, 0x88, 0x99, 0xc6, 0x8d, 0x45, 0x3e, 0x3f, 0xd2,
	0x96, 0x4b, 0x4a, 0xa3, 0xe8, 0xaa, 0xf1, 0x05, 0x35, 0xee, 0x19, 0xae, 0x38, 0x8d, 0x7c, 0xd7,
	0x8a, 0x45, 0x66, 0x10, 0xa1, 0xd6, 0x52, 0x1b, 0xda, 0x1e, 0x35, 0xc6, 0x9d, 0x59, 0x3f, 0xad,
	0x21, 0xa5, 0xcb, 0x22, 0x5e, 0x1f, 0x15, 0x66, 0x3f, 0x5f, 0x26, 0x9f, 0xf0, 0x7f, 0xe1, 0x46,
	0x64, 0xf8, 0x71, 0x40, 0x63, 0x4b, 0xa4, 0xe0, 0x0a, 0x52, 0x78, 0x05, 0xa9, 0xf1, 0x27, 0x52,
	0xb3, 0x86, 0x94, 0x2c, 0x21, 0xfe, 0xfd, 0x23, 0x32, 0x00, 0x30, 0x76, 0x63, 0x0f, 0x66, 0x21,
	0xb9, 0x9f, 0xde, 0xca, 0x2a, 0x0e, 0xa1, 0xd0, 0x7e, 0x47, 0x63, 0x36, 0xbb, 0xd3, 0x6b, 0x9f,
	0xe4, 0xec, 0x09, 0x62, 0xbf, 0xa7, 0xc7, 0x9c, 0x91, 0x07, 0x88, 0x3c, 0x10, 0x19, 0x5c, 0xe0,
	0x9f, 0x91, 0xf6, 0x87, 0x17, 0xf9, 0xf9, 0xb6, 0x93, 0x7f, 0xf3, 0x9b, 0xe7, 0x5e, 0xed, 0x6c,
	0xb6, 0x91, 0xbb, 0x96, 0xfb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x52, 0x79, 0x34, 0x50,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketSvcClient is the client API for TicketSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketSvcClient interface {
	// create new ticket
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TicketResponse, error)
}

type ticketSvcClient struct {
	cc *grpc.ClientConn
}

func NewTicketSvcClient(cc *grpc.ClientConn) TicketSvcClient {
	return &ticketSvcClient{cc}
}

func (c *ticketSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, "/pb.ticketsvc.v1.TicketSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketSvcServer is the server API for TicketSvc service.
type TicketSvcServer interface {
	// create new ticket
	Create(context.Context, *CreateRequest) (*TicketResponse, error)
}

// UnimplementedTicketSvcServer can be embedded to have forward compatible implementations.
type UnimplementedTicketSvcServer struct {
}

func (*UnimplementedTicketSvcServer) Create(ctx context.Context, req *CreateRequest) (*TicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterTicketSvcServer(s *grpc.Server, srv TicketSvcServer) {
	s.RegisterService(&_TicketSvc_serviceDesc, srv)
}

func _TicketSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ticketsvc.v1.TicketSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ticketsvc.v1.TicketSvc",
	HandlerType: (*TicketSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TicketSvc_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ticketsvc/v1/ticketsvc.proto",
}
