// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ticketsvc/v1/ticketsvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// get request
type GetRequest struct {
	// unique id of ticket
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// list response
type ListResponse struct {
	// list of tickets
	Data                 []*TicketResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{1}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetData() []*TicketResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

// list request
type ListRequest struct {
	// org id
	OrgId string `protobuf:"bytes,1,opt,name=orgId,proto3" json:"orgId,omitempty"`
	// created by
	CreatedBy            string   `protobuf:"bytes,2,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *ListRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// ticket response
type TicketResponse struct {
	// unique id of ticket
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OrgId       string `protobuf:"bytes,4,opt,name=orgId,proto3" json:"orgId,omitempty"`
	CreatedBy   string `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// reference id of ticket
	ReferenceId          string       `protobuf:"bytes,6,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TicketResponse) Reset()         { *m = TicketResponse{} }
func (m *TicketResponse) String() string { return proto.CompactTextString(m) }
func (*TicketResponse) ProtoMessage()    {}
func (*TicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{3}
}

func (m *TicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TicketResponse.Unmarshal(m, b)
}
func (m *TicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TicketResponse.Marshal(b, m, deterministic)
}
func (m *TicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TicketResponse.Merge(m, src)
}
func (m *TicketResponse) XXX_Size() int {
	return xxx_messageInfo_TicketResponse.Size(m)
}
func (m *TicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TicketResponse proto.InternalMessageInfo

func (m *TicketResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TicketResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TicketResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TicketResponse) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *TicketResponse) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *TicketResponse) GetReferenceId() string {
	if m != nil {
		return m.ReferenceId
	}
	return ""
}

func (m *TicketResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// create ticket request
type CreateRequest struct {
	// title of ticket
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// description of ticket
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// org id of ticket
	OrgId string `protobuf:"bytes,3,opt,name=orgId,proto3" json:"orgId,omitempty"`
	// id of user creating this ticket
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{4}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *CreateRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d6faa99461a7b25, []int{5}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "pb.ticketsvc.v1.GetRequest")
	proto.RegisterType((*ListResponse)(nil), "pb.ticketsvc.v1.ListResponse")
	proto.RegisterType((*ListRequest)(nil), "pb.ticketsvc.v1.ListRequest")
	proto.RegisterType((*TicketResponse)(nil), "pb.ticketsvc.v1.TicketResponse")
	proto.RegisterType((*CreateRequest)(nil), "pb.ticketsvc.v1.CreateRequest")
	proto.RegisterType((*ErrorType)(nil), "pb.ticketsvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/ticketsvc/v1/ticketsvc.proto", fileDescriptor_9d6faa99461a7b25) }

var fileDescriptor_9d6faa99461a7b25 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x1f, 0x94, 0x74, 0x50, 0x88, 0x1b, 0x0f, 0x0d, 0x22, 0x90, 0x9e, 0x38, 0x95, 0x00,
	0xbf, 0x40, 0x08, 0x21, 0x44, 0x4f, 0x95, 0x93, 0xb7, 0xd2, 0x8e, 0xa4, 0x51, 0x69, 0xdd, 0x5d,
	0x9a, 0x10, 0xff, 0xad, 0x07, 0x7f, 0x87, 0xe9, 0x2e, 0xb5, 0xa5, 0x0d, 0xe8, 0x71, 0x66, 0x5e,
	0xdf, 0xbc, 0xf7, 0xba, 0x03, 0xbd, 0x78, 0x3d, 0xe4, 0xa1, 0xff, 0x8a, 0x9c, 0x25, 0xfe, 0x30,
	0x19, 0xe5, 0x85, 0x13, 0xd3, 0x88, 0x47, 0xa4, 0x15, 0xaf, 0x9d, 0xbc, 0x97, 0x8c, 0xec, 0x0e,
	0xc0, 0x02, 0xb9, 0x8b, 0x1f, 0x3b, 0x64, 0x9c, 0x34, 0x41, 0x0d, 0x03, 0x4b, 0xe9, 0x2b, 0x03,
	0xd3, 0x55, 0xc3, 0xc0, 0x9e, 0xc1, 0xe5, 0x63, 0xc8, 0xb8, 0x8b, 0x2c, 0x8e, 0xb6, 0x0c, 0xc9,
	0x04, 0xf4, 0xc0, 0xe3, 0x9e, 0xa5, 0xf4, 0xb5, 0x41, 0x63, 0xdc, 0x73, 0x4a, 0x6c, 0xce, 0x4a,
	0x14, 0x19, 0xdc, 0x15, 0x60, 0xfb, 0x1e, 0x1a, 0x92, 0x44, 0xee, 0xb8, 0x81, 0x5a, 0x44, 0x37,
	0xcb, 0x6c, 0x8d, 0x2c, 0x48, 0x07, 0x4c, 0x9f, 0xa2, 0xc7, 0x31, 0x98, 0xee, 0x2d, 0x55, 0x4c,
	0xf2, 0x86, 0xfd, 0xa5, 0x40, 0xf3, 0x98, 0xbb, 0x2c, 0x35, 0xa5, 0xe5, 0x21, 0x7f, 0xc3, 0xc3,
	0xc7, 0xb2, 0x20, 0x7d, 0x68, 0x04, 0xc8, 0x7c, 0x1a, 0xc6, 0x3c, 0x8c, 0xb6, 0x96, 0x26, 0x66,
	0xc5, 0x56, 0x2e, 0x47, 0x3f, 0x29, 0xa7, 0x56, 0x92, 0x93, 0xb2, 0x52, 0x7c, 0x41, 0x8a, 0x5b,
	0x1f, 0x97, 0x81, 0x65, 0x48, 0xd6, 0x42, 0x8b, 0x8c, 0xc1, 0x40, 0x4a, 0x23, 0xca, 0xac, 0xba,
	0x88, 0xaa, 0x5d, 0x89, 0x6a, 0x9e, 0x8e, 0x57, 0xfb, 0x18, 0xdd, 0x03, 0xd2, 0xfe, 0x84, 0xab,
	0x99, 0x58, 0x51, 0x48, 0x4a, 0x5a, 0x52, 0xce, 0x58, 0x52, 0xcf, 0x58, 0xd2, 0x4e, 0x5a, 0xd2,
	0xcb, 0x09, 0xcf, 0xc1, 0xfc, 0x55, 0x44, 0xba, 0x00, 0x8c, 0x7b, 0x7c, 0xc7, 0x66, 0x51, 0x20,
	0xb7, 0xd7, 0xdc, 0x42, 0x87, 0x58, 0x50, 0x7f, 0x47, 0xc6, 0xbc, 0x4d, 0x96, 0x76, 0x56, 0x8e,
	0xbf, 0x15, 0x30, 0xe5, 0x8f, 0x7a, 0x4a, 0x7c, 0xf2, 0x00, 0x86, 0x74, 0x44, 0xba, 0x15, 0xff,
	0x47, 0x56, 0xdb, 0x7f, 0x3d, 0x25, 0xfb, 0x82, 0xcc, 0x41, 0x4f, 0x9f, 0x11, 0xe9, 0x54, 0xa0,
	0x85, 0xd7, 0xd5, 0xbe, 0x3b, 0x31, 0x2d, 0xd0, 0x68, 0x0b, 0xe4, 0xe4, 0xb6, 0x82, 0xcb, 0xcf,
	0xe0, 0x1f, 0x6a, 0xa6, 0xd7, 0xcf, 0xad, 0xd2, 0xad, 0xad, 0x0d, 0x71, 0x62, 0x93, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x96, 0x9e, 0x14, 0x75, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketSvcClient is the client API for TicketSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketSvcClient interface {
	// create new ticket
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TicketResponse, error)
	// list tickets
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// get ticket
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*TicketResponse, error)
}

type ticketSvcClient struct {
	cc *grpc.ClientConn
}

func NewTicketSvcClient(cc *grpc.ClientConn) TicketSvcClient {
	return &ticketSvcClient{cc}
}

func (c *ticketSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, "/pb.ticketsvc.v1.TicketSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketSvcClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/pb.ticketsvc.v1.TicketSvc/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketSvcClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*TicketResponse, error) {
	out := new(TicketResponse)
	err := c.cc.Invoke(ctx, "/pb.ticketsvc.v1.TicketSvc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketSvcServer is the server API for TicketSvc service.
type TicketSvcServer interface {
	// create new ticket
	Create(context.Context, *CreateRequest) (*TicketResponse, error)
	// list tickets
	List(context.Context, *ListRequest) (*ListResponse, error)
	// get ticket
	Get(context.Context, *GetRequest) (*TicketResponse, error)
}

// UnimplementedTicketSvcServer can be embedded to have forward compatible implementations.
type UnimplementedTicketSvcServer struct {
}

func (*UnimplementedTicketSvcServer) Create(ctx context.Context, req *CreateRequest) (*TicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTicketSvcServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTicketSvcServer) Get(ctx context.Context, req *GetRequest) (*TicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterTicketSvcServer(s *grpc.Server, srv TicketSvcServer) {
	s.RegisterService(&_TicketSvc_serviceDesc, srv)
}

func _TicketSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ticketsvc.v1.TicketSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketSvc_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketSvcServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ticketsvc.v1.TicketSvc/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketSvcServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketSvc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketSvcServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ticketsvc.v1.TicketSvc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketSvcServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ticketsvc.v1.TicketSvc",
	HandlerType: (*TicketSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TicketSvc_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _TicketSvc_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TicketSvc_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/ticketsvc/v1/ticketsvc.proto",
}
