// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/signupsvc/v1/signupsvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// sign up request
type SignUpRequest struct {
	// first name of user
	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// email address of user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// password of user
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// confirm password
	ConfirmPassword      string   `protobuf:"bytes,5,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1259e5b1116da6b8, []int{0}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

// sign up response
type SignUpResponse struct {
	// aws cognito id of user
	AwsUserSub           string       `protobuf:"bytes,1,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	FirstName            string       `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string       `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string       `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1259e5b1116da6b8, []int{1}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

func (m *SignUpResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SignUpResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SignUpResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignUpResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1259e5b1116da6b8, []int{2}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SignUpRequest)(nil), "pb.registrationsvc.v1.SignUpRequest")
	proto.RegisterType((*SignUpResponse)(nil), "pb.registrationsvc.v1.SignUpResponse")
	proto.RegisterType((*ErrorType)(nil), "pb.registrationsvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/signupsvc/v1/signupsvc.proto", fileDescriptor_1259e5b1116da6b8) }

var fileDescriptor_1259e5b1116da6b8 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xfd, 0xd2, 0x36, 0xfd, 0xcc, 0x15, 0x2d, 0x0e, 0x0a, 0xa1, 0x88, 0x96, 0xa0, 0xd0, 0x55,
	0x4a, 0xeb, 0xc6, 0xb5, 0xd2, 0xad, 0x48, 0x6a, 0x11, 0xdc, 0x4d, 0x9a, 0x69, 0x18, 0x68, 0x32,
	0xe3, 0xdc, 0x49, 0x8a, 0x0f, 0xe4, 0x4b, 0xf8, 0x74, 0x92, 0x4c, 0xd2, 0xa6, 0xc5, 0xea, 0xf2,
	0xfc, 0x0c, 0x9c, 0x73, 0xe6, 0xc2, 0xb5, 0x0c, 0x47, 0xc8, 0xe3, 0x34, 0x93, 0x98, 0x2f, 0x46,
	0xf9, 0x78, 0x0b, 0x7c, 0xa9, 0x84, 0x16, 0xe4, 0x42, 0x86, 0xbe, 0x62, 0x31, 0x47, 0xad, 0xa8,
	0xe6, 0x22, 0x2d, 0x94, 0x7c, 0xec, 0x7d, 0x5a, 0x70, 0x32, 0xe3, 0x71, 0x3a, 0x97, 0x01, 0x7b,
	0xcf, 0x18, 0x6a, 0x72, 0x09, 0xce, 0x92, 0x2b, 0xd4, 0x4f, 0x34, 0x61, 0xae, 0x35, 0xb0, 0x86,
	0x4e, 0xb0, 0x25, 0x48, 0x1f, 0x8e, 0x56, 0xb4, 0x12, 0x5b, 0xa5, 0xb8, 0xc1, 0xe4, 0x1c, 0x6c,
	0x96, 0x50, 0xbe, 0x72, 0xdb, 0xa5, 0x60, 0x40, 0xf1, 0x42, 0x52, 0xc4, 0xb5, 0x50, 0x91, 0xdb,
	0x31, 0x2f, 0x6a, 0x4c, 0x86, 0xd0, 0x5b, 0x88, 0x74, 0xc9, 0x55, 0xf2, 0x5c, 0x5b, 0xec, 0xd2,
	0xb2, 0x4f, 0x7b, 0x5f, 0x16, 0x9c, 0xd6, 0x39, 0x51, 0x8a, 0x14, 0x19, 0xb9, 0x02, 0xa0, 0x6b,
	0x9c, 0x23, 0x53, 0xb3, 0x2c, 0xac, 0x92, 0x36, 0x98, 0xdd, 0x22, 0xad, 0xdf, 0x8a, 0xb4, 0x0f,
	0x15, 0xe9, 0x34, 0x8b, 0xdc, 0x43, 0x97, 0x29, 0x25, 0x14, 0xba, 0xf6, 0xa0, 0x3d, 0x3c, 0x9e,
	0x0c, 0xfc, 0x1f, 0x27, 0xf5, 0xa7, 0x85, 0xe9, 0xe5, 0x43, 0xb2, 0xa0, 0xf2, 0x7b, 0x53, 0x70,
	0x36, 0x64, 0x11, 0x1b, 0x35, 0xd5, 0x19, 0x3e, 0x8a, 0xc8, 0x0c, 0x6c, 0x07, 0x0d, 0x86, 0xb8,
	0xf0, 0x3f, 0x61, 0x88, 0x34, 0xae, 0x43, 0xd7, 0x70, 0x12, 0x81, 0x63, 0x26, 0x98, 0xe5, 0x0b,
	0xf2, 0x0a, 0x5d, 0x03, 0xc8, 0xcd, 0x81, 0x1c, 0x3b, 0xdf, 0xda, 0xbf, 0xfd, 0xc3, 0x65, 0x46,
	0xf5, 0xfe, 0x3d, 0x9c, 0xbd, 0xf5, 0xf6, 0x6e, 0x29, 0xec, 0x96, 0x27, 0x74, 0xf7, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x36, 0xfb, 0x9f, 0x84, 0x65, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SignUpSvcClient is the client API for SignUpSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SignUpSvcClient interface {
	// sign up new user
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
}

type signUpSvcClient struct {
	cc *grpc.ClientConn
}

func NewSignUpSvcClient(cc *grpc.ClientConn) SignUpSvcClient {
	return &signUpSvcClient{cc}
}

func (c *signUpSvcClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/pb.registrationsvc.v1.SignUpSvc/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignUpSvcServer is the server API for SignUpSvc service.
type SignUpSvcServer interface {
	// sign up new user
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
}

// UnimplementedSignUpSvcServer can be embedded to have forward compatible implementations.
type UnimplementedSignUpSvcServer struct {
}

func (*UnimplementedSignUpSvcServer) SignUp(ctx context.Context, req *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}

func RegisterSignUpSvcServer(s *grpc.Server, srv SignUpSvcServer) {
	s.RegisterService(&_SignUpSvc_serviceDesc, srv)
}

func _SignUpSvc_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignUpSvcServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.registrationsvc.v1.SignUpSvc/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignUpSvcServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SignUpSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.registrationsvc.v1.SignUpSvc",
	HandlerType: (*SignUpSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _SignUpSvc_SignUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/signupsvc/v1/signupsvc.proto",
}
