// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/registrationsvc/v1/registrationsvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// register request
type RegisterRequest struct {
	// first name of user
	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	// last name of user
	LastName string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	// email address of user
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// password of user
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// confirm password
	ConfirmPassword      string   `protobuf:"bytes,5,opt,name=confirmPassword,proto3" json:"confirmPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ad5f245eaa35e9d, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

// register response
type RegisterResponse struct {
	// aws cognito id of user
	AwsUserSub           string       `protobuf:"bytes,1,opt,name=awsUserSub,proto3" json:"awsUserSub,omitempty"`
	FirstName            string       `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string       `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string       `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ad5f245eaa35e9d, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetAwsUserSub() string {
	if m != nil {
		return m.AwsUserSub
	}
	return ""
}

func (m *RegisterResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *RegisterResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *RegisterResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ad5f245eaa35e9d, []int{2}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "pb.registrationsvc.v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "pb.registrationsvc.v1.RegisterResponse")
	proto.RegisterType((*ErrorType)(nil), "pb.registrationsvc.v1.ErrorType")
}

func init() {
	proto.RegisterFile("pb/registrationsvc/v1/registrationsvc.proto", fileDescriptor_5ad5f245eaa35e9d)
}

var fileDescriptor_5ad5f245eaa35e9d = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcb, 0x4a, 0xf3, 0x40,
	0x18, 0xfd, 0xd3, 0x36, 0xfd, 0x9b, 0xcf, 0x45, 0x65, 0xb0, 0x18, 0x8a, 0x48, 0xc8, 0x42, 0x03,
	0x42, 0x4a, 0xeb, 0xc6, 0xb5, 0xd2, 0xad, 0x48, 0xaa, 0x1b, 0xc1, 0xc5, 0x24, 0x9d, 0x96, 0x40,
	0x93, 0x19, 0xe7, 0x9b, 0xa4, 0xf8, 0x44, 0xbe, 0x84, 0x0f, 0x27, 0xb9, 0x4c, 0x1b, 0x43, 0xab,
	0xcb, 0x73, 0x19, 0xe6, 0x9c, 0x33, 0x03, 0x37, 0x22, 0x9c, 0x48, 0xb6, 0x8e, 0x51, 0x49, 0xaa,
	0x62, 0x9e, 0x62, 0x1e, 0x4d, 0xf2, 0x69, 0x9b, 0xf2, 0x85, 0xe4, 0x8a, 0x93, 0x91, 0x08, 0xfd,
	0xb6, 0x92, 0x4f, 0xdd, 0x4f, 0x03, 0x86, 0x41, 0x49, 0x33, 0x19, 0xb0, 0xf7, 0x8c, 0xa1, 0x22,
	0x17, 0x60, 0xad, 0x62, 0x89, 0xea, 0x91, 0x26, 0xcc, 0x36, 0x1c, 0xc3, 0xb3, 0x82, 0x3d, 0x41,
	0xc6, 0x30, 0xd8, 0xd0, 0x5a, 0xec, 0x94, 0xe2, 0x0e, 0x93, 0x33, 0x30, 0x59, 0x42, 0xe3, 0x8d,
	0xdd, 0x2d, 0x85, 0x0a, 0x14, 0x27, 0x04, 0x45, 0xdc, 0x72, 0xb9, 0xb4, 0x7b, 0xd5, 0x09, 0x8d,
	0x89, 0x07, 0xc3, 0x88, 0xa7, 0xab, 0x58, 0x26, 0x4f, 0xda, 0x62, 0x96, 0x96, 0x36, 0xed, 0x7e,
	0x19, 0x70, 0xba, 0x4f, 0x8a, 0x82, 0xa7, 0xc8, 0xc8, 0x25, 0x00, 0xdd, 0xe2, 0x0b, 0x32, 0xb9,
	0xc8, 0xc2, 0x3a, 0x6b, 0x83, 0xf9, 0x59, 0xa5, 0xf3, 0x5b, 0x95, 0xee, 0xb1, 0x2a, 0xbd, 0x66,
	0x95, 0x3b, 0xe8, 0x33, 0x29, 0xb9, 0x44, 0xdb, 0x74, 0xba, 0xde, 0xc9, 0xcc, 0xf1, 0x0f, 0xce,
	0xea, 0xcf, 0x0b, 0xd3, 0xf3, 0x87, 0x60, 0x41, 0xed, 0x77, 0xe7, 0x60, 0xed, 0xc8, 0x22, 0x36,
	0x2a, 0xaa, 0x32, 0x7c, 0xe0, 0xcb, 0x6a, 0x62, 0x33, 0x68, 0x30, 0xc4, 0x86, 0xff, 0x09, 0x43,
	0xa4, 0x6b, 0x1d, 0x5a, 0xc3, 0x99, 0xd0, 0xcf, 0x55, 0x5d, 0xb7, 0xc8, 0x23, 0xf2, 0x06, 0x03,
	0xbd, 0x0b, 0xb9, 0x3a, 0x92, 0xa7, 0xf5, 0xc4, 0xe3, 0xeb, 0x3f, 0x7d, 0xd5, 0xc0, 0xee, 0xbf,
	0xfb, 0xf3, 0xd7, 0xd1, 0xc1, 0x7f, 0x16, 0xf6, 0xcb, 0x8f, 0x75, 0xfb, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xd0, 0x2e, 0xcf, 0x62, 0x87, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistrationSvcClient is the client API for RegistrationSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationSvcClient interface {
	// register new user
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registrationSvcClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationSvcClient(cc *grpc.ClientConn) RegistrationSvcClient {
	return &registrationSvcClient{cc}
}

func (c *registrationSvcClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/pb.registrationsvc.v1.RegistrationSvc/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationSvcServer is the server API for RegistrationSvc service.
type RegistrationSvcServer interface {
	// register new user
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedRegistrationSvcServer can be embedded to have forward compatible implementations.
type UnimplementedRegistrationSvcServer struct {
}

func (*UnimplementedRegistrationSvcServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterRegistrationSvcServer(s *grpc.Server, srv RegistrationSvcServer) {
	s.RegisterService(&_RegistrationSvc_serviceDesc, srv)
}

func _RegistrationSvc_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationSvcServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.registrationsvc.v1.RegistrationSvc/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationSvcServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistrationSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.registrationsvc.v1.RegistrationSvc",
	HandlerType: (*RegistrationSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _RegistrationSvc_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/registrationsvc/v1/registrationsvc.proto",
}
