// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/casesvc/v1/casesvc.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// case response
type CaseResponse struct {
	// unique id of case
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Descritption string `protobuf:"bytes,3,opt,name=descritption,proto3" json:"descritption,omitempty"`
	OrgId        string `protobuf:"bytes,4,opt,name=orgId,proto3" json:"orgId,omitempty"`
	// reference id of case
	ReferenceId          string       `protobuf:"bytes,5,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	Errors               []*ErrorType `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CaseResponse) Reset()         { *m = CaseResponse{} }
func (m *CaseResponse) String() string { return proto.CompactTextString(m) }
func (*CaseResponse) ProtoMessage()    {}
func (*CaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7670596bad00a352, []int{0}
}

func (m *CaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseResponse.Unmarshal(m, b)
}
func (m *CaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseResponse.Marshal(b, m, deterministic)
}
func (m *CaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseResponse.Merge(m, src)
}
func (m *CaseResponse) XXX_Size() int {
	return xxx_messageInfo_CaseResponse.Size(m)
}
func (m *CaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CaseResponse proto.InternalMessageInfo

func (m *CaseResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CaseResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CaseResponse) GetDescritption() string {
	if m != nil {
		return m.Descritption
	}
	return ""
}

func (m *CaseResponse) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *CaseResponse) GetReferenceId() string {
	if m != nil {
		return m.ReferenceId
	}
	return ""
}

func (m *CaseResponse) GetErrors() []*ErrorType {
	if m != nil {
		return m.Errors
	}
	return nil
}

// create case request
type CreateRequest struct {
	// title of case
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// description of case
	Descritption string `protobuf:"bytes,2,opt,name=descritption,proto3" json:"descritption,omitempty"`
	// org id of case
	OrgId                string   `protobuf:"bytes,3,opt,name=orgId,proto3" json:"orgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7670596bad00a352, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetDescritption() string {
	if m != nil {
		return m.Descritption
	}
	return ""
}

func (m *CreateRequest) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

// error type
type ErrorType struct {
	// http error code
	StatusCode int32 `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	// error detail
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorType) Reset()         { *m = ErrorType{} }
func (m *ErrorType) String() string { return proto.CompactTextString(m) }
func (*ErrorType) ProtoMessage()    {}
func (*ErrorType) Descriptor() ([]byte, []int) {
	return fileDescriptor_7670596bad00a352, []int{2}
}

func (m *ErrorType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorType.Unmarshal(m, b)
}
func (m *ErrorType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorType.Marshal(b, m, deterministic)
}
func (m *ErrorType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorType.Merge(m, src)
}
func (m *ErrorType) XXX_Size() int {
	return xxx_messageInfo_ErrorType.Size(m)
}
func (m *ErrorType) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorType.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorType proto.InternalMessageInfo

func (m *ErrorType) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *ErrorType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CaseResponse)(nil), "pb.casesvc.v1.CaseResponse")
	proto.RegisterType((*CreateRequest)(nil), "pb.casesvc.v1.CreateRequest")
	proto.RegisterType((*ErrorType)(nil), "pb.casesvc.v1.ErrorType")
}

func init() { proto.RegisterFile("pb/casesvc/v1/casesvc.proto", fileDescriptor_7670596bad00a352) }

var fileDescriptor_7670596bad00a352 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x85, 0x0a, 0x4d, 0xa7, 0x45, 0x93, 0x8d, 0x87, 0x8d, 0x35, 0x86, 0x70, 0xea, 0x89,
	0xda, 0xfa, 0x06, 0x12, 0x0e, 0xbd, 0x19, 0xf4, 0xe4, 0xc5, 0x00, 0x3b, 0x36, 0x24, 0xca, 0xae,
	0x3b, 0x5b, 0x12, 0x5f, 0xcf, 0x27, 0x33, 0x2c, 0xa2, 0xd0, 0x43, 0x6f, 0x3b, 0xff, 0xbf, 0x93,
	0xf9, 0x66, 0x7e, 0x58, 0xaa, 0x62, 0x5d, 0xe6, 0x84, 0xd4, 0x94, 0xeb, 0x66, 0xd3, 0x3f, 0x63,
	0xa5, 0xa5, 0x91, 0x2c, 0x50, 0x45, 0xdc, 0x2b, 0xcd, 0x26, 0xfa, 0x76, 0x60, 0x91, 0xe4, 0x84,
	0x19, 0x92, 0x92, 0x35, 0x21, 0xbb, 0x00, 0xb7, 0x12, 0xdc, 0x09, 0x9d, 0xd5, 0x2c, 0x73, 0x2b,
	0xc1, 0xae, 0xc0, 0x33, 0x95, 0x79, 0x47, 0xee, 0x5a, 0xa9, 0x2b, 0x58, 0x04, 0x0b, 0x81, 0x54,
	0xea, 0xca, 0x28, 0x53, 0xc9, 0x9a, 0x4f, 0xac, 0x39, 0xd2, 0xda, 0x4e, 0xa9, 0xf7, 0x3b, 0xc1,
	0xcf, 0xbb, 0x4e, 0x5b, 0xb0, 0x10, 0xe6, 0x1a, 0xdf, 0x50, 0x63, 0x5d, 0xe2, 0x4e, 0x70, 0xcf,
	0x7a, 0x43, 0x89, 0xdd, 0x81, 0x8f, 0x5a, 0x4b, 0x4d, 0xdc, 0x0f, 0x27, 0xab, 0xf9, 0x96, 0xc7,
	0x23, 0xe4, 0x38, 0x6d, 0xcd, 0xe7, 0x2f, 0x85, 0xd9, 0xef, 0xbf, 0xe8, 0x15, 0x82, 0x44, 0x63,
	0x6e, 0x30, 0xc3, 0xcf, 0x03, 0x92, 0xf9, 0x87, 0x76, 0x4e, 0x41, 0xbb, 0xa7, 0xa0, 0x27, 0x03,
	0xe8, 0x28, 0x85, 0xd9, 0xdf, 0x54, 0x76, 0x0b, 0x40, 0x26, 0x37, 0x07, 0x4a, 0xa4, 0xe8, 0x26,
	0x78, 0xd9, 0x40, 0x61, 0x1c, 0xa6, 0x1f, 0x48, 0x94, 0xef, 0xfb, 0x9b, 0xf5, 0xe5, 0xf6, 0x11,
	0xa6, 0xed, 0xad, 0x9f, 0x9a, 0x92, 0xa5, 0xe0, 0x77, 0xc8, 0xec, 0xe6, 0x68, 0xbd, 0xd1, 0x26,
	0xd7, 0xcb, 0x63, 0x77, 0x90, 0x55, 0x74, 0xf6, 0x70, 0xf9, 0x12, 0x8c, 0xc2, 0x2e, 0x7c, 0x9b,
	0xf2, 0xfd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xe1, 0x37, 0x62, 0x04, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CaseSvcClient is the client API for CaseSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CaseSvcClient interface {
	// create new case
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CaseResponse, error)
}

type caseSvcClient struct {
	cc *grpc.ClientConn
}

func NewCaseSvcClient(cc *grpc.ClientConn) CaseSvcClient {
	return &caseSvcClient{cc}
}

func (c *caseSvcClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CaseResponse, error) {
	out := new(CaseResponse)
	err := c.cc.Invoke(ctx, "/pb.casesvc.v1.CaseSvc/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaseSvcServer is the server API for CaseSvc service.
type CaseSvcServer interface {
	// create new case
	Create(context.Context, *CreateRequest) (*CaseResponse, error)
}

// UnimplementedCaseSvcServer can be embedded to have forward compatible implementations.
type UnimplementedCaseSvcServer struct {
}

func (*UnimplementedCaseSvcServer) Create(ctx context.Context, req *CreateRequest) (*CaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterCaseSvcServer(s *grpc.Server, srv CaseSvcServer) {
	s.RegisterService(&_CaseSvc_serviceDesc, srv)
}

func _CaseSvc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaseSvcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.casesvc.v1.CaseSvc/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaseSvcServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CaseSvc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.casesvc.v1.CaseSvc",
	HandlerType: (*CaseSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CaseSvc_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/casesvc/v1/casesvc.proto",
}
